DROP TABLE PF_APP_ADMIN CASCADE CONSTRAINTS;

DROP TABLE PF_APP_BASE CASCADE CONSTRAINTS;

DROP TABLE PF_APP_DOMAIN CASCADE CONSTRAINTS;

DROP TABLE PF_APP_PROFILE CASCADE CONSTRAINTS;

DROP TABLE PF_APP_RSA_KEY_PAIR CASCADE CONSTRAINTS;

DROP TABLE PF_ENTITY CASCADE CONSTRAINTS;

DROP TABLE PF_ENTITY_PROPERTY CASCADE CONSTRAINTS;

DROP TABLE PF_LOG_LOGIN CASCADE CONSTRAINTS;

DROP TABLE PF_LOG_VISIT CASCADE CONSTRAINTS;

DROP TABLE PF_MENU CASCADE CONSTRAINTS;

DROP TABLE PF_MENU_I18N CASCADE CONSTRAINTS;

DROP TABLE PF_MENU_SHORT CASCADE CONSTRAINTS;

DROP TABLE PF_PARAM_DEF CASCADE CONSTRAINTS;

DROP TABLE PF_PARAM_LIST_ENUM CASCADE CONSTRAINTS;

DROP TABLE PF_PARAM_REGION_ENUM CASCADE CONSTRAINTS;

DROP TABLE PF_PARAM_SINGLE CASCADE CONSTRAINTS;

DROP TABLE PF_PARAM_TREE_ENUM CASCADE CONSTRAINTS;

DROP TABLE PF_PERM CASCADE CONSTRAINTS;

DROP TABLE PF_ROLE CASCADE CONSTRAINTS;

DROP TABLE PF_ROLE_PERM CASCADE CONSTRAINTS;

DROP TABLE PF_USER CASCADE CONSTRAINTS;

DROP TABLE PF_USER_PASSWORD CASCADE CONSTRAINTS;

DROP TABLE PF_USER_PROFILE CASCADE CONSTRAINTS;

DROP TABLE PF_USER_ROLE CASCADE CONSTRAINTS;

DROP TABLE PF_USER_STATE CASCADE CONSTRAINTS;
