logging:
  pattern:
    # 在日志中添加请求信息 org.autumn.commons.web.request.AutumnRequests.AUTUMN_REQUEST_HEADER_NAME
    level: "%X{AUTUMN_REQUEST} %5p"

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  profiles:
    active:
      - h2
  application:
    name: autumn-admin
  resources:
    static-locations:
      - file:static/
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: autumn
    password: autumn
  data:
    web:
      pageable:
        prefix: page.
        one-indexed-parameters: true # 分页数从1开始
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort # 表示排序的参数名称

mybatis:
  mapper-locations:
    - classpath*:/org/autumn/**/*.sqlmapper.xml

autumn:
  swagger2:
    host: localhost:${server.port}
    context-path: ${server.servlet.context-path:''}
    api:
      title: ${spring.application.name}
      description: 基于Autumn开发的后台管理端

---
spring:
  profiles: h2
  datasource:
    platform: h2
    url: jdbc:log4jdbc:h2:~/autumn
  h2:
    console:
      enabled: true
---
spring:
  profiles: mysql
  datasource:
    platform: mysql
    url: jdbc:log4jdbc:MySQL://localhost:3306/autumn2?characterEncoding=utf8


